builds:
  - id: "giraffecloud"
    binary: "giraffecloud"
    main: "./cmd/giraffecloud"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X giraffecloud/internal/version.Version={{.Version}}
      - -X giraffecloud/internal/version.BuildTime={{.Date}}
      - -X giraffecloud/internal/version.GitCommit={{.FullCommit}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: osa911
    name: giraffecloud
  name_template: "Release {{.Version}}"
  draft: false
  prerelease: auto
