// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClientVersionsColumns holds the columns for the "client_versions" table.
	ClientVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "channel", Type: field.TypeString, Default: "stable"},
		{Name: "platform", Type: field.TypeString, Default: "all"},
		{Name: "arch", Type: field.TypeString, Default: "all"},
		{Name: "latest_version", Type: field.TypeString},
		{Name: "minimum_version", Type: field.TypeString},
		{Name: "download_url", Type: field.TypeString},
		{Name: "release_notes", Type: field.TypeString, Nullable: true},
		{Name: "auto_update_enabled", Type: field.TypeBool, Default: true},
		{Name: "force_update", Type: field.TypeBool, Default: false},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ClientVersionsTable holds the schema information for the "client_versions" table.
	ClientVersionsTable = &schema.Table{
		Name:       "client_versions",
		Columns:    ClientVersionsColumns,
		PrimaryKey: []*schema.Column{ClientVersionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "clientversion_channel_platform_arch",
				Unique:  true,
				Columns: []*schema.Column{ClientVersionsColumns[1], ClientVersionsColumns[2], ClientVersionsColumns[3]},
			},
		},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "monthly_limit_bytes", Type: field.TypeInt64, Default: 107374182400},
		{Name: "overage_per_gb_cents", Type: field.TypeInt, Default: 0},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_used", Type: field.TypeTime},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "user_sessions", Type: field.TypeUint32},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TokensColumns holds the columns for the "tokens" table.
	TokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUint32},
	}
	// TokensTable holds the schema information for the "tokens" table.
	TokensTable = &schema.Table{
		Name:       "tokens",
		Columns:    TokensColumns,
		PrimaryKey: []*schema.Column{TokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tokens_users_tokens",
				Columns:    []*schema.Column{TokensColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TunnelsColumns holds the columns for the "tunnels" table.
	TunnelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "domain", Type: field.TypeString, Unique: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "client_ip", Type: field.TypeString, Nullable: true},
		{Name: "is_enabled", Type: field.TypeBool, Default: true},
		{Name: "target_port", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeUint32},
	}
	// TunnelsTable holds the schema information for the "tunnels" table.
	TunnelsTable = &schema.Table{
		Name:       "tunnels",
		Columns:    TunnelsColumns,
		PrimaryKey: []*schema.Column{TunnelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tunnels_users_tunnels",
				Columns:    []*schema.Column{TunnelsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsagesColumns holds the columns for the "usages" table.
	UsagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "period_start", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUint32},
		{Name: "tunnel_id", Type: field.TypeUint32, Nullable: true},
		{Name: "domain", Type: field.TypeString, Default: ""},
		{Name: "bytes_in", Type: field.TypeInt64, Default: 0},
		{Name: "bytes_out", Type: field.TypeInt64, Default: 0},
		{Name: "requests", Type: field.TypeInt64, Default: 0},
	}
	// UsagesTable holds the schema information for the "usages" table.
	UsagesTable = &schema.Table{
		Name:       "usages",
		Columns:    UsagesColumns,
		PrimaryKey: []*schema.Column{UsagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "usage_period_start_user_id_tunnel_id_domain",
				Unique:  true,
				Columns: []*schema.Column{UsagesColumns[3], UsagesColumns[4], UsagesColumns[5], UsagesColumns[6]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "firebase_uid", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
		{Name: "last_login_ip", Type: field.TypeString, Nullable: true},
		{Name: "last_activity", Type: field.TypeTime, Nullable: true},
		{Name: "plan_name", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClientVersionsTable,
		PlansTable,
		SessionsTable,
		TokensTable,
		TunnelsTable,
		UsagesTable,
		UsersTable,
	}
)

func init() {
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	TokensTable.ForeignKeys[0].RefTable = UsersTable
	TunnelsTable.ForeignKeys[0].RefTable = UsersTable
}
