-- Create "users" table
CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "firebase_uid" character varying NOT NULL, "email" character varying NOT NULL, "name" character varying NULL DEFAULT '', "role" character varying NOT NULL DEFAULT 'user', "is_active" boolean NOT NULL DEFAULT true, "last_login" timestamptz NULL, "last_login_ip" character varying NULL, "last_activity" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create index "users_firebase_uid_key" to table: "users"
CREATE UNIQUE INDEX "users_firebase_uid_key" ON "public"."users" ("firebase_uid");
-- Create "sessions" table
CREATE TABLE "public"."sessions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "token" character varying NOT NULL, "expires_at" timestamptz NOT NULL, "last_used" timestamptz NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "user_agent" character varying NULL, "ip_address" character varying NULL, "user_sessions" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "sessions_users_sessions" FOREIGN KEY ("user_sessions") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "sessions_token_key" to table: "sessions"
CREATE UNIQUE INDEX "sessions_token_key" ON "public"."sessions" ("token");
