-- Create "client_versions" table
CREATE TABLE "public"."client_versions" ("id" character varying NOT NULL, "channel" character varying NOT NULL DEFAULT 'stable', "platform" character varying NOT NULL DEFAULT 'all', "arch" character varying NOT NULL DEFAULT 'all', "latest_version" character varying NOT NULL, "minimum_version" character varying NOT NULL, "download_url" character varying NOT NULL, "release_notes" character varying NULL, "auto_update_enabled" boolean NOT NULL DEFAULT true, "force_update" boolean NOT NULL DEFAULT false, "metadata" jsonb NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "clientversion_channel_platform_arch" to table: "client_versions"
CREATE UNIQUE INDEX "clientversion_channel_platform_arch" ON "public"."client_versions" ("channel", "platform", "arch");
-- Create "tunnels" table
CREATE TABLE "public"."tunnels" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "domain" character varying NOT NULL, "token" character varying NOT NULL, "client_ip" character varying NULL, "is_active" boolean NOT NULL DEFAULT true, "target_port" bigint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tunnels_users_tunnels" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "tunnels_domain_key" to table: "tunnels"
CREATE UNIQUE INDEX "tunnels_domain_key" ON "public"."tunnels" ("domain");
-- Create index "tunnels_token_key" to table: "tunnels"
CREATE UNIQUE INDEX "tunnels_token_key" ON "public"."tunnels" ("token");
