-- Modify "users" table
ALTER TABLE "public"."users" ADD COLUMN "plan_name" character varying NULL;
-- Create "plans" table
CREATE TABLE "public"."plans" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying NOT NULL, "monthly_limit_bytes" bigint NOT NULL DEFAULT 107374182400, "overage_per_gb_cents" bigint NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"));
-- Create index "plans_name_key" to table: "plans"
CREATE UNIQUE INDEX "plans_name_key" ON "public"."plans" ("name");
