.PHONY: help setup-dev setup-prod validate-env db-init db-migrate db-migrate-create db-migrate-revert db-reset db-backup db-restore db-init-prod db-migrate-prod db-recreate-prod db-backup-prod db-restore-prod dev dev-hot prod build build-client test db-gen db-migrate-status db-hash proto-check proto-gen proto-clean proto-verify release release-dry-run snapshot caddy-start caddy-stop caddy-reload

help:
	@echo "GiraffeCloud Makefile Commands"
	@echo ""
	@echo "Environment Setup:"
	@echo "  setup-dev     - Set up development environment file"
	@echo "  setup-prod    - Set up production environment file"
	@echo ""
	@echo "Database Commands:"
	@echo "  Common:"
	@echo "    db-gen              - Generate Ent code"
	@echo "    db-hash             - Generate hash for migrations"
	@echo "    db-migrate-status   - Show migration status"
	@echo ""
	@echo "  Development:"
	@echo "    db-init             - Initialize development database"
	@echo "    db-reset           - Reset development database (requires FORCE=1)"
	@echo "    db-migrate-create  - Create a new migration (requires NAME=migration_name)"
	@echo "    db-migrate-apply   - Apply pending migrations"
	@echo "    db-migrate-revert  - Revert last migration (requires FORCE=1 N=number)"
	@echo "    db-backup          - Backup development database"
	@echo "    db-restore         - Restore development database from backup (requires BACKUP=path)"
	@echo ""
	@echo "  Production (use with caution):"
	@echo "    db-init-prod           - Initialize production database"
	@echo "    db-migrate-prod        - Apply migrations to production"
	@echo "                             FORCE=1 for dry-run"
	@echo "                             FORCE=1 CONFIRM=1 to apply"
	@echo "    db-recreate-prod       - Recreate production database (requires FORCE=1)"
	@echo "    db-backup-prod         - Backup production database"
	@echo "    db-restore-prod        - Restore production database"
	@echo "                             (requires BACKUP=path FORCE=1)"
	@echo "    set-min-version        - Set minimum client version (dev)"
	@echo "                             (requires VERSION=v1.1.0)"
	@echo "    set-min-version-prod   - Set minimum client version (production)"
	@echo "                             (requires VERSION=v1.1.0)"
	@echo ""
	@echo "Server:"
	@echo "  dev          - Run development server with hybrid tunnels (production-grade)"
	@echo "  dev-hot      - Run development server with hot-reload and Caddy"
	@echo "  prod         - Run production server"
	@echo "  build        - Build server with hybrid tunnel support"
	@echo "  build-client - Build CLI client with hybrid tunnel support"
	@echo "  test         - Run tests"
	@echo "  test-tunnel  - Run hybrid tunnel tests"
	@echo ""
	@echo "Protobuf:"
	@echo "  proto-check  - Check if protobuf tools are installed"
	@echo "  proto-gen    - Generate Go code from protobuf files"
	@echo "  proto-clean  - Remove generated protobuf files"
	@echo "  proto-verify - Verify protobuf files are up to date"
	@echo ""
	@echo "Caddy:"
	@echo "  caddy-start  - Start Caddy reverse proxy server"
	@echo "  caddy-stop   - Stop Caddy server"
	@echo "  caddy-reload - Reload Caddy configuration"
	@echo ""
	@echo "Release Management:"
	@echo "  release-dry-run  - Test the release process without publishing"
	@echo "  release         - Create and publish a new release"
	@echo "  snapshot        - Create a snapshot release for testing"