.PHONY: help setup-dev setup-prod validate-env db-init db-migrate db-rollback db-reset db-backup db-restore db-init-prod db-migrate-prod db-rollback-prod db-reset-prod db-backup-prod db-restore-prod dev dev-hot prod build test

help:
	@echo "GiraffeCloud Makefile Commands"
	@echo ""
	@echo "Environment Setup:"
	@echo "  setup-dev     - Set up development environment file"
	@echo "  setup-prod    - Set up production environment file"
	@echo ""
	@echo "Database Development:"
	@echo "  db-init      - Initialize development database"
	@echo "  db-migrate   - Run database migrations"
	@echo "  db-rollback  - Rollback last migration"
	@echo "  db-reset     - Reset development database"
	@echo "  db-backup    - Create development database backup"
	@echo "  db-restore   - Restore development database from backup"
	@echo ""
	@echo "Database Production:"
	@echo "  db-init-prod    - Initialize production database"
	@echo "  db-migrate-prod - Run production migrations"
	@echo "  db-rollback-prod- Rollback last production migration"
	@echo "  db-reset-prod   - Reset production database"
	@echo "  db-backup-prod  - Create production database backup"
	@echo "  db-restore-prod - Restore production database from backup"
	@echo ""
	@echo "Server:"
	@echo "  dev          - Run development server"
	@echo "  dev-hot      - Run development server with hot-reload"
	@echo "  prod         - Run production server"
	@echo "  build        - Build application binary"
	@echo "  test         - Run tests"