name: Go Format & Build Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fmt-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Verify formatting
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "These files are not gofmt-formatted:" && echo "$UNFORMATTED"
            exit 1
          fi
      - name: Build
        run: go build ./...
